[package]
name = "dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
ipnet = "2.5"
itertools = "0.10"
rand = "0.8"
